// Package runplan provides the RunPlan Resolver and related types.
package runplan

// ResolvedRunPlan is the frozen run specification sent to the Agent.
type ResolvedRunPlan struct {
	Image         string            `json:"image"`
	ContainerName string            `json:"container_name"`
	Entrypoint    []string          `json:"entrypoint,omitempty"`
	Args          []string          `json:"args"`
	Env           map[string]string `json:"env"`

	Privileged  bool              `json:"privileged,omitempty"`
	IPCMode     string            `json:"ipc_mode,omitempty"`
	UTSMode     string            `json:"uts_mode,omitempty"`
	NetworkMode string            `json:"network_mode,omitempty"`
	ShmSize     string            `json:"shm_size,omitempty"`
	Ulimits     map[string]string `json:"ulimits,omitempty"`

	Devices  []DeviceMapping `json:"devices,omitempty"`
	Mounts   []MountMapping  `json:"mounts,omitempty"`
	GroupAdd []string        `json:"group_add,omitempty"`

	HostPort      int `json:"host_port"`
	ContainerPort int `json:"container_port"`

	DeviceBinding    *DeviceBinding `json:"device_binding,omitempty"`
	GPUDeviceIDs     []string       `json:"gpu_device_ids,omitempty"`
	GPUVisibleEnvKey string         `json:"gpu_visible_env_key,omitempty"`
	GpuDriver        string         `json:"gpu_driver,omitempty"`       // DeviceRequest driver, e.g. "" for docker run --gpus CLI
	GpuCapabilities  [][]string     `json:"gpu_capabilities,omitempty"` // e.g. [["gpu"]]

	SecurityOptions []string `json:"security_options,omitempty"`
	ExtraArgs       []string `json:"extra_args,omitempty"`

	HealthCheck HealthCheck `json:"health_check,omitempty"`

	// ParameterSourceMap records the source chain for every final output field.
	// Covers args, env, mounts, ports, devices, docker_options, health_check, resource_controls.
	// Storage: resolved_run_plans.plan_json.parameter_source_map
	// See docs/reports/runtime-architecture-parameter-final-state/06-runplan-and-preflight-contract.md
	ParameterSourceMap *ParameterSourceMap `json:"parameter_source_map,omitempty"`

	// Hash identifiers
	InputHash string `json:"input_hash"`
	PlanHash  string `json:"plan_hash"`

	// Audit references
	BackendName     string `json:"backend_name"`
	BackendVersion  string `json:"backend_version"`
	ModelName       string `json:"model_name"`
	ModelPath       string `json:"model_path"`
	ServedModelName string `json:"served_model_name"`
	DeploymentID    string `json:"deployment_id"`
	InstanceID      string `json:"instance_id"`
}

// ============================================================================
// Parameter Source Map — records provenance for every final ResolvedRunPlan field
// ============================================================================

// ParameterSourceMap records the effective source for every output field in a
// ResolvedRunPlan. It is generated by the RunPlan resolver and persisted alongside
// the plan for audit, debugging, and UI preview.
type ParameterSourceMap struct {
	Args             []ParameterSourceEntry `json:"args"`
	Env              []ParameterSourceEntry `json:"env"`
	Mounts           []ParameterSourceEntry `json:"mounts"`
	Ports            []ParameterSourceEntry `json:"ports"`
	Devices          []ParameterSourceEntry `json:"devices"`
	DockerOptions    []ParameterSourceEntry `json:"docker_options"`
	HealthCheck      []ParameterSourceEntry `json:"health_check"`
	ResourceControls []ParameterSourceEntry `json:"resource_controls"`
	SystemGenerated  []ParameterSourceEntry `json:"system_generated"`
}

// ParameterSourceEntry records the provenance of a single final parameter value.
type ParameterSourceEntry struct {
	Key             string             `json:"key"`
	Target          string             `json:"target"`        // args, env, mounts, ports, devices, docker_options, health_check
	Arg             string             `json:"arg,omitempty"` // CLI flag name, e.g. --gpu-memory-utilization
	Value           any                `json:"value"`
	EffectiveSource string             `json:"effective_source"` // default, backend_version, backend_runtime, node_backend_runtime, deployment_override, system_generated, runtime_detected
	ConfigSetKey    string             `json:"config_set_key,omitempty"`
	LastValueLayer  string             `json:"last_value_layer"`
	SourceChain     []SourceChainEntry `json:"source_chain,omitempty"`
}

// SourceChainEntry is one step in a parameter's provenance chain.
// Reuses the catalog.SourceChainEntry shape for consistency.
type SourceChainEntry struct {
	Layer  string `json:"layer"`
	Value  any    `json:"value"`
	Reason string `json:"reason"`
}

// DeviceMapping maps a host device to a container device.
type DeviceMapping struct {
	HostPath      string `json:"host_path"`
	ContainerPath string `json:"container_path"`
	Permissions   string `json:"permissions,omitempty"`
}

// MountMapping maps a host path to a container path.
type MountMapping struct {
	HostPath      string `json:"host_path"`
	ContainerPath string `json:"container_path"`
	Readonly      bool   `json:"readonly,omitempty"`
}

// HealthCheck defines the container health check configuration.
type HealthCheck struct {
	Path                  string `json:"path"`
	ExpectedStatus        int    `json:"expected_status"`
	StartupTimeoutSeconds int    `json:"startup_timeout_seconds"`
	IntervalSeconds       int    `json:"interval_seconds"`
	TimeoutSeconds        int    `json:"timeout_seconds"`
}

// DeviceBinding is the neutral placement/resource binding captured in the
// resolved plan. Docker-specific rendering is derived from this, not exposed as
// backend parameters.
type DeviceBinding struct {
	Vendor          string   `json:"vendor,omitempty"`
	GPUDeviceIDs    []string `json:"gpu_device_ids,omitempty"`
	VisibleEnvKey   string   `json:"visible_env_key,omitempty"`
	VisibleEnvValue string   `json:"visible_env_value,omitempty"`
	DockerGPUOption string   `json:"docker_gpu_option,omitempty"`
}
