id: runtime.sglang.nvidia-docker
name: SGLang NVIDIA Docker
display_name: SGLang NVIDIA Docker
backend_id: backend.sglang
backend_version_id: sglang-v0.5.13.post1
slug: sglang-nvidia-docker
managed_by: system
runner_type: docker
vendor: nvidia
image_ref: lmsysorg/sglang:latest

model_mount:
  container_path: /models
  readonly: true
docker_options:
  ipc_mode: host
  shm_size: 32gb
  gpu_driver: ""
  gpu_capabilities: [["gpu"]]
env:
  CUDA_VISIBLE_DEVICES: "{{vendor_visible_devices}}"
verification:
  status: verified
