// Package token provides Agent Token bootstrapping for Server and Agent.
//
// On first startup, the Server auto-generates a secure random token and writes it
// to runtime/security/agent-token.env. The Agent reads from the same file.
//
// Environment variable LIGHTAI_AGENT_TOKEN always takes precedence.
// Non-default tokens in config files are always respected.
package token

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	// DefaultTokenValue is the default placeholder token in example configs.
	DefaultTokenValue = "lightai-agent-token-change-me"
	// DevTokenValue is a secondary default used in dev configs.
	DevTokenValue = "dev-agent-token"
	// TokenFile is the path relative to the runtime directory.
	TokenFile = "runtime/security/agent-token.env"
	// TokenDirPerm is the permission for the security directory.
	TokenDirPerm = 0700
	// TokenFilePerm is the permission for the token file.
	TokenFilePerm = 0600
	// TokenLength is the number of random bytes (hex-encoded, so 2x chars).
	TokenLength = 32
)

// IsDefault returns true if the token is the default placeholder or empty.
func IsDefault(token string) bool {
	return token == "" || token == DefaultTokenValue || token == DevTokenValue
}

// ReadFromFile reads the agent token from runtime/security/agent-token.env.
// The file format is one line: LIGHTAI_AGENT_TOKEN=<token>
func ReadFromFile() (string, error) {
	data, err := os.ReadFile(TokenFile)
	if err != nil {
		return "", err
	}
	content := strings.TrimSpace(string(data))
	// Support both formats: bare token and KEY=VALUE.
	if strings.HasPrefix(content, "LIGHTAI_AGENT_TOKEN=") {
		return strings.TrimPrefix(content, "LIGHTAI_AGENT_TOKEN="), nil
	}
	return content, nil
}

// FileExists returns true if the token file already exists.
func FileExists() bool {
	_, err := os.Stat(TokenFile)
	return err == nil
}

// Generate creates a cryptographically secure random hex token.
func Generate() (string, error) {
	b := make([]byte, TokenLength)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("generate token: %w", err)
	}
	return hex.EncodeToString(b), nil
}

// WriteToFile writes the token to runtime/security/agent-token.env.
// Creates parent directories with 0700, writes file with 0600.
func WriteToFile(token string) error {
	dir := filepath.Dir(TokenFile)
	if err := os.MkdirAll(dir, TokenDirPerm); err != nil {
		return fmt.Errorf("create token directory: %w", err)
	}
	if err := os.WriteFile(TokenFile, []byte(token+"\n"), TokenFilePerm); err != nil {
		return fmt.Errorf("write token file: %w", err)
	}
	return nil
}

// BootstrapServer resolves the agent token for the Server process.
//
// Precedence:
//  1. LIGHTAI_AGENT_TOKEN env var (already applied by config loader)
//  2. Non-default token in config file
//  3. Existing runtime/security/agent-token.env
//  4. Auto-generate and persist to file (first startup)
//
// Returns the resolved token, whether it was auto-generated, and any error.
func BootstrapServer(currentToken string) (token string, autoGenerated bool, err error) {
	// Env / config already took precedence — if it's non-default, use it.
	if !IsDefault(currentToken) {
		return currentToken, false, nil
	}

	// Try existing file.
	if FileExists() {
		t, err := ReadFromFile()
		if err != nil {
			return "", false, fmt.Errorf("read existing token file %s: %w", TokenFile, err)
		}
		return t, false, nil
	}

	// First startup: generate.
	t, err := Generate()
	if err != nil {
		return "", false, err
	}
	if err := WriteToFile(t); err != nil {
		return "", false, err
	}
	return t, true, nil
}

// BootstrapAgent resolves the agent token for the Agent process.
//
// Precedence:
//  1. LIGHTAI_AGENT_TOKEN env var (already applied by config loader)
//  2. Non-default token in config file
//  3. Existing runtime/security/agent-token.env (shared with local Server)
//
// Unlike the Server, the Agent never auto-generates a token.
// If no token is found, it returns an error with a clear help message.
func BootstrapAgent(currentToken string) (string, error) {
	// Env / config already took precedence.
	if !IsDefault(currentToken) {
		return currentToken, nil
	}

	// Try local shared file.
	if FileExists() {
		t, err := ReadFromFile()
		if err != nil {
			return "", fmt.Errorf("read token file %s: %w", TokenFile, err)
		}
		return t, nil
	}

	// No token available — agent cannot auto-generate.
	return "", fmt.Errorf(
		"no agent token configured\n"+
			"  • Set LIGHTAI_AGENT_TOKEN environment variable, or\n"+
			"  • Copy %s from the Server installation, or\n"+
			"  • Set agent_token in the Agent config file",
		TokenFile,
	)
}
