apiVersion: lightai/v1
kind: BackendRuntimeTemplate
metadata:
  name: sglang-nvidia-docker
spec:
  displayName: "sglang 0.4.6 nvidia Docker"
  backendName: "sglang"
  backendVersion: "0.4.6"
  vendor: "nvidia"
  runtimeType: docker
  imageName: "lmsysorg/sglang:v0.4.6"
  imagePullPolicy: if_not_present
  entrypoint: []
  argsOverride: []
  defaultEnv: {}
  docker:
    privileged: true
    ipcMode: "host"
    shmSize: "10g"
    devices: []
  modelMount: {}
  healthCheckOverride: {}
