apiVersion: lightai/v1
kind: BackendRuntimeTemplate
metadata:
  name: vllm-metax-docker
spec:
  displayName: "vllm 0.8.5 metax Docker"
  backendName: "vllm"
  backendVersion: "0.8.5"
  vendor: "metax"
  runtimeType: docker
  imageName: "registry.local/vllm-openai:v0.8.5-metax"
  imagePullPolicy: if_not_present
  entrypoint: []
  argsOverride: []
  defaultEnv: {}
  docker:
    privileged: true
    ipcMode: "host"
    shmSize: "10g"
    devices: [{"host_path":"/dev/mxcd","container_path":"/dev/mxcd"},{"host_path":"/dev/dri","container_path":"/dev/dri"}]
  modelMount: {}
  healthCheckOverride: {}
