apiVersion: lightai/v1
kind: BackendRuntimeTemplate
metadata:
  name: vllm-nvidia-docker
spec:
  displayName: "vllm 0.8.5 nvidia Docker"
  backendName: "vllm"
  backendVersion: "0.8.5"
  vendor: "nvidia"
  runtimeType: docker
  imageName: "vllm/vllm-openai:v0.8.5"
  imagePullPolicy: if_not_present
  entrypoint: []
  argsOverride: []
  defaultEnv: {}
  docker:
    privileged: true
    ipcMode: "host"
    shmSize: "10g"
    devices: []
  modelMount: {}
  healthCheckOverride: {}
